Print a more useful error on old direnv versions

diff --git a/direnvrc b/direnvrc
--- a/direnvrc
+++ b/direnvrc
@@ -1,13 +1,16 @@
 # shellcheck shell=bash
 
-# Usage: nix_direnv_version <version_at_least>
-#
-# Checks that the nix-direnv version is at least as old as <version_at_least>.
+REQUIRED_DIRENV_VERSION="2.21.3"
 
-if ! has direnv_version || ! direnv_version 2.21.3; then
+
+if ! has direnv_version || ! direnv_version "$REQUIRED_DIRENV_VERSION" 2>/dev/null; then
+  printf '%s\n' "nix-direnv: base direnv version is older than the required v$REQUIRED_DIRENV_VERSION." >&2
   exit 1
 fi
 
+# Usage: nix_direnv_version <version_at_least>
+#
+# Checks that the nix-direnv version is at least as old as <version_at_least>.
 nix_direnv_version() {
   declare major='1' minor='5' patch='1' # UPDATE(nix-direnv version)
 
